version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_mir
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_HOST=${DB_HOST}
      - DATABASE_PORT=${DB_PORT}
    env_file:
      - .env
    ports:
      - '8000:8000'
    entrypoint: sh -c "alembic upgrade head && uvicorn src.main:app --host 0.0.0.0 --port 8000"
    networks:
      - mir_network
    depends_on:
      - postgresql_db
      - redis_app
      - mongo_db

  postgresql_db:
    container_name: postgresql_db_mir
    image: postgres:latest
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_HOST=${DB_HOST}
      - DATABASE_PORT=${DB_PORT}
    env_file:
      - .env
    ports:
      - ${DB_PORT}:${DB_PORT}
    networks:
      mir_network:
        ipv4_address: 192.168.0.10

  redis_app:
    container_name: redis_mir
    image: redis:latest
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli", "ping"]
      interval: 5s
      timeout: 10s
      retries: 3
    networks:
      mir_network:
        ipv4_address: 192.168.0.17

  mongo_db:
    container_name: mongo_db_mir
    image: mongo:latest
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    networks:
      mir_network:
        ipv4_address: 192.168.0.18

networks:
  mir_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.0.0/24
